# Generated by Django 4.2 on 2023-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('status', models.CharField(choices=[('publushed', 'Опубликован'), ('chern', 'Не опубликован')], default='chern', max_length=30)),
            ],
        ),
    ]
