# Generated by Django 4.2 on 2023-04-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
                ('chanel_id', models.CharField(max_length=100)),
                ('start_time', models.TimeField(default='00:00:00', null=True)),
                ('end_time', models.TimeField(default='00:00:00', null=True)),
                ('type', models.CharField(choices=[('sourse', 'Исходный канал'), ('dependent', 'Зависимый')], default='dependent', max_length=20)),
                ('active', models.BooleanField(choices=[(True, 'Активен'), (False, 'Не активен')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OriginPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('post_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChanelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_post_id', models.IntegerField(null=True)),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.chanel')),
                ('origin_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.originpost')),
            ],
        ),
    ]
