# Generated by Django 4.2 on 2023-04-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chanel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterModelOptions(
            name='chanelpost',
            options={'verbose_name': 'Пост канала', 'verbose_name_plural': 'Посты канала'},
        ),
        migrations.AlterModelOptions(
            name='originpost',
            options={'verbose_name': 'Пост исходного канала', 'verbose_name_plural': 'Посты исходного канала'},
        ),
        migrations.AddField(
            model_name='chanel',
            name='language',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en')], default='en', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='active',
            field=models.BooleanField(choices=[(True, 'Активен'), (False, 'Не активен')], default=False, verbose_name='Статус канала'),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='chanel_id',
            field=models.CharField(max_length=100, verbose_name='id канала'),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='end_time',
            field=models.TimeField(default='00:00:00', null=True, verbose_name='Окончание работы канала'),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='name',
            field=models.CharField(null=True, verbose_name='Название канала'),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='start_time',
            field=models.TimeField(default='00:00:00', null=True, verbose_name='Начало работы канала'),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='type',
            field=models.CharField(choices=[('sourse', 'Исходный канал'), ('dependent', 'Зависимый')], default='dependent', max_length=20, verbose_name='Тип канала'),
        ),
    ]
