# Generated by Django 4.2 on 2023-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.IntegerField(null=True),
        ),
    ]
