# Generated by Django 4.2 on 2023-04-14 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_chanel_options_alter_chanelpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originpost',
            name='chanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chanel'),
        ),
    ]
