# Generated by Django 4.2 on 2023-04-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='post_id',
        ),
    ]
