# Generated by Django 4.2 on 2023-04-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_originpost_chanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originpost',
            name='chanel',
        ),
    ]
