# Generated by Django 4.2 on 2023-04-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_originpost_chanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='originpost',
            name='chanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.chanel'),
        ),
    ]
