# Generated by Django 4.2 on 2023-04-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_post_chanel_to_id_remove_post_status_chanel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chanel',
            old_name='post_id',
            new_name='post',
        ),
    ]
