# Generated by Django 4.2 on 2023-04-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_post_id_chanel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='origin_post_id',
        ),
        migrations.RemoveField(
            model_name='chanel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='chanel',
            name='self_post_id',
        ),
        migrations.RemoveField(
            model_name='chanel',
            name='status',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='OriginPost',
        ),
        migrations.CreateModel(
            name='ChanelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_post_id', models.IntegerField(null=True)),
                ('published', models.BooleanField(null=True)),
                ('origin_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.originpost')),
            ],
        ),
        migrations.AddField(
            model_name='chanel',
            name='posts',
            field=models.ManyToManyField(to='bot.chanelpost'),
        ),
    ]
