# Generated by Django 4.2 on 2023-04-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_chanelpost_edited_alter_chanelpost_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='chanelpost',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='chanelpost',
            name='published',
        ),
        migrations.AddField(
            model_name='chanel',
            name='chanel_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chanel',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='chanel',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='chanelpost',
            name='chanel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.chanel'),
        ),
    ]
