# Generated by Django 4.2 on 2023-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_chanel_posts_remove_chanelpost_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='end_time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='start_time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
